name:  CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        working-directory: prueba
        run: dotnet restore prueba.csproj

      - name: Build project
        working-directory: prueba
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        working-directory: prueba.Tests
        run: dotnet test --no-build --configuration Release

  build-push:
    if: github.event_name == 'push'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-app:latest
